### ISSUE TITLE
CallObjectMethodA

### ISSUE THREAD

**Issue by meiguo1231** [ClarkGuan/jni#3]
env.CallObjectMethodA()

如何给java传递String 参数呢？

**Comment by ClarkGuan** [comment]
> env.CallObjectMethodA()
> 
> 如何给java传递String 参数呢？

<img width="988" alt="image" src="https://github.com/ClarkGuan/jni/assets/7122493/6f82c62d-35ca-4cfa-ba0f-4d4d15e166a1">
使用这个函数
