### ISSUE TITLE
env.go:588:21: error: no member named 'GetModule' in 'struct JNINativeInterface'

### ISSUE THREAD

**Issue by aadog** [ClarkGuan/jni#4]
# github.com/ClarkGuan/jni
vendor\github.com\ClarkGuan\jni\env.go:588:21: error: no member named 'GetModule' in 'struct JNINativeInterface'
     return (*env)->GetModule(env, clazz);
            ~~~~~~  ^
1 error generated.

**Comment by ClarkGuan** [comment]
@aadog Android 的 JNI 头文件中并没有 GetModule 的实现，我会去掉它们。
